
version: '3.1'
services:

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./back-end/data:/var/lib/mysql
